baseURL = "https://godopty.github.io/godopty/"
locale = "en-us"
title = "godopty"
theme = "blowfish"
publishDir = "../docs"
sectionPagesMenu = "docs"

[params]
  [params.author]
    name = "godopty"
  defaultTheme = "dark"
  showCopyright = true
  showSidebar = true
  [params.sidebar]
    compact = false
    [params.sidebar.home]
      show = false
    [params.sidebar.list]
      show = true
    [params.sidebar.single]
      show = true

[params.list]
  showBreadcrumbs = false

[params.homepage]
  showRecent = false

[[menu.main]]
  name = "Docs"
  pageRef = "/docs"
  weight = 10

[[menu.main]]
  name = "Releases"
  url = "https://github.com/godopty/godopty/releases"
  weight = 20

[[menu.main]]
  name = "GitHub"
  url = "https://github.com/godopty/godopty"
  weight = 30
