[[main]]
  name = "Docs"
  pageRef = "/docs"
  weight = 10

[[main]]
  name = "Releases"
  url = "https://github.com/godopty/godopty/releases"
  weight = 20

[[main]]
  name = "GitHub"
  url = "https://github.com/godopty/godopty"
  weight = 30
