locale = "en-us"
title = "godopty"

[author]
  name = "godopty"

colorScheme = "slate"
defaultAppearance = "dark"
autoSwitchAppearance = false
showCopyright = false
showBreadcrumbs = true

[homepage]
  layout = "page"
  showRecent = false

[article]
  showDate = false
  showReadingTime = false
  showWordCount = false
  showAuthor = false
  showTaxonomies = false
  showPagination = false
  showTableOfContents = false
  showHeadingAnchors = true

[list]
  showBreadcrumbs = false
  groupByYear = false
  showSummary = false
