//! Cross-platform PTY lifecycle via [`portable_pty`].
//!
//! Spawns a shell process connected to a pseudo-terminal, runs a
//! dedicated I/O thread for reading, and exposes write/resize operations.
//! Each PTY uses one OS thread.

use std::io::{Read, Write};
use std::thread;

use portable_pty::{CommandBuilder, MasterPty, PtySize, native_pty_system};
use tokio::sync::mpsc::UnboundedSender;

/// Environment variables that may not be set via pane/profile config.
/// These are dynamic-loader injection vectors: a shared or imported
/// layout carrying one of them would run arbitrary code in every shell
/// spawned from it. Users can still set them manually inside a shell.
const BLOCKED_ENV_KEYS: &[&str] = &[
    "LD_PRELOAD",
    "LD_AUDIT",
    "LD_LIBRARY_PATH",
    "LD_ORIGIN_PATH",
    "DYLD_INSERT_LIBRARIES",
    "DYLD_LIBRARY_PATH",
    "DYLD_FALLBACK_LIBRARY_PATH",
    "DYLD_FORCE_FLAT_NAMESPACE",
    "GPTY_EVENT_SOCKET",
    "GPTY_EVENT_PROTOCOL",
    "GPTY_TERMINAL_SESSION_ID",
    "GPTY_EVENT_CAPABILITY",
];

/// Process-wide control credentials must never leak into child shells.
const STRIPPED_INHERITED_ENV_KEYS: &[&str] = &["GPTY_SECRET", "GPTY_SOCKET", "GPTY_GUI"];

/// Filter `KEY=VALUE` environment entries from settings/layouts/profiles.
///
/// Drops entries without `=`, with an empty or malformed key (must match
/// `[A-Za-z_][A-Za-z0-9_]*`), and keys in [`BLOCKED_ENV_KEYS`] (exact
/// case match — case variants are inert for the dynamic loaders).
pub fn sanitize_envs(envs: &[String]) -> Vec<(String, String)> {
    let mut out = Vec::with_capacity(envs.len());
    for e in envs {
        let Some((k, v)) = e.split_once('=') else {
            continue;
        };
        let k = k.trim();
        let v = v.trim();
        let mut chars = k.chars();
        let valid = chars
            .next()
            .is_some_and(|c| c.is_ascii_alphabetic() || c == '_')
            && chars.all(|c| c.is_ascii_alphanumeric() || c == '_');
        if !valid || BLOCKED_ENV_KEYS.contains(&k) {
            continue;
        }
        out.push((k.to_string(), v.to_string()));
    }
    out
}
const DEFAULT_ROWS: u16 = 24;
const DEFAULT_COLS: u16 = 80;
const READ_BUF_SIZE: usize = 4096;
/// A handle to a spawned PTY: shell process + I/O thread.
pub struct PtyHandle {
    pub id: u32,
    writer: Box<dyn Write + Send>,
    master: Box<dyn MasterPty + Send>,
    _child: Box<dyn portable_pty::Child + Send + Sync>,
    _read_thread: thread::JoinHandle<()>,
}

impl Drop for PtyHandle {
    fn drop(&mut self) {
        let _ = self._child.kill();
        // Non-blocking reap: try_wait returns immediately.
        // If the child hasn't exited yet (brief race after kill),
        // the zombie is reaped when the process eventually exits.
        let _ = self._child.try_wait();
    }
}

impl PtyHandle {
    /// Spawn a shell process in a new PTY and start a reader thread.
    /// Output bytes are sent to `tx` as `Vec<u8>` chunks.
    pub fn spawn(
        id: u32,
        command: &str,
        args: &[&str],
        envs: &[String],
        trusted_envs: &[(String, String)],
        tx: UnboundedSender<Vec<u8>>,
    ) -> Result<Self, Box<dyn std::error::Error + Send + Sync>> {
        let pty_system = native_pty_system();
        let mut cmd = CommandBuilder::new(command);
        cmd.args(args);
        for key in STRIPPED_INHERITED_ENV_KEYS {
            cmd.env_remove(key);
        }
        cmd.env("TERM", "xterm-256color");
        for (k, v) in sanitize_envs(envs) {
            cmd.env(k, v);
        }
        // Trusted runtime values are generated by gpty and applied last. They
        // are never accepted from persisted pane/profile environment data.
        for (k, v) in trusted_envs {
            cmd.env(k, v);
        }

        let pty_pair = pty_system.openpty(PtySize {
            rows: DEFAULT_ROWS,
            cols: DEFAULT_COLS,
            pixel_width: 0,
            pixel_height: 0,
        })?;
        let child = pty_pair.slave.spawn_command(cmd)?;
        let mut reader = pty_pair.master.try_clone_reader()?;
        let writer = pty_pair.master.take_writer()?;
        let master = pty_pair.master;

        let read_thread = thread::Builder::new()
            .name(format!("pty-reader-{id}"))
            .spawn(move || {
                let mut buf = [0u8; READ_BUF_SIZE];
                loop {
                    match reader.read(&mut buf) {
                        Ok(0) => break,
                        Ok(n) => {
                            if tx.send(buf[..n].to_vec()).is_err() {
                                break;
                            }
                        }
                        Err(e) => {
                            log::error!("[PTY {id}] Read error: {e}");
                            break;
                        }
                    }
                }
            })?;

        Ok(Self {
            id,
            writer,
            master,
            _child: child,
            _read_thread: read_thread,
        })
    }

    /// Write a line to the PTY (appends `\r` = Enter).
    pub fn write_line(&mut self, line: &str) -> Result<(), std::io::Error> {
        self.writer.write_all(line.as_bytes())?;
        self.writer.write_all(b"\r")?;
        self.writer.flush()
    }

    /// Write raw bytes to the PTY (no newline appended).
    pub fn write_bytes(&mut self, data: &[u8]) -> Result<(), std::io::Error> {
        self.writer.write_all(data)?;
        self.writer.flush()
    }

    /// Resize the PTY — sends SIGWINCH to the child process.
    pub fn resize(
        &self,
        rows: u16,
        cols: u16,
    ) -> Result<(), Box<dyn std::error::Error + Send + Sync>> {
        self.master.resize(PtySize {
            rows,
            cols,
            pixel_width: 0,
            pixel_height: 0,
        })?;
        Ok(())
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    fn s(v: &str) -> String {
        v.to_string()
    }

    #[test]
    fn sanitize_envs_drops_blocked_keys() {
        let envs = vec![
            s("LD_PRELOAD=/evil.so"),
            s("LD_AUDIT=/evil.so"),
            s("DYLD_INSERT_LIBRARIES=/evil.dylib"),
            s("GPTY_EVENT_SOCKET=/tmp/fake.sock"),
            s("GPTY_EVENT_CAPABILITY=stolen"),
            s("PATH=/usr/bin"),
        ];
        assert_eq!(
            sanitize_envs(&envs),
            vec![("PATH".to_string(), "/usr/bin".to_string())]
        );
    }

    #[test]
    fn sanitize_envs_blocklist_is_case_sensitive() {
        // Lowercase variants are inert for the dynamic loaders.
        let envs = vec![s("ld_preload=/x.so")];
        assert_eq!(
            sanitize_envs(&envs),
            vec![("ld_preload".to_string(), "/x.so".to_string())]
        );
    }

    #[test]
    fn sanitize_envs_drops_malformed_keys() {
        let envs = vec![
            s("-X=y"),
            s("1A=b"),
            s("=novalue"),
            s("no_equals"),
            s("A B=c"),
            s("OK=yes"),
        ];
        assert_eq!(
            sanitize_envs(&envs),
            vec![("OK".to_string(), "yes".to_string())]
        );
    }

    #[test]
    fn sanitize_envs_trims_key_and_value() {
        let envs = vec![s("  PATH = /usr/bin  ")];
        assert_eq!(
            sanitize_envs(&envs),
            vec![("PATH".to_string(), "/usr/bin".to_string())]
        );
    }
}
