#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"

# Copy repo docs into assets/repo/ for Hugo resources.Get
mkdir -p assets/repo/crates/godopty-core
mkdir -p assets/repo/crates/godopty-gdext
mkdir -p assets/repo/godot

cp ../README.md assets/repo/
cp ../CHANGELOG.md assets/repo/
cp ../ROADMAP.md assets/repo/
cp ../AGENTS.md assets/repo/
cp ../crates/godopty-core/README.md assets/repo/crates/godopty-core/
cp ../crates/godopty-gdext/README.md assets/repo/crates/godopty-gdext/
cp ../godot/README.md assets/repo/godot/

# ── Generate Versions dropdown from GitHub releases API ──────────────────
python3 << 'PYEOF'
import json, os, time, urllib.request, sys

CACHE_DIR = ".cache"
CACHE_FILE = os.path.join(CACHE_DIR, "releases.json")
DATA_FILE = "data/versions.yaml"
REPO = "godopty/godopty"
CACHE_TTL = 3600

def fetch():
    url = f"https://api.github.com/repos/{REPO}/releases?per_page=5"
    req = urllib.request.Request(url, headers={"User-Agent": "godopty-docs-setup"})
    with urllib.request.urlopen(req, timeout=10) as resp:
        return json.loads(resp.read())

releases = None
if os.path.exists(CACHE_FILE):
    age = time.time() - os.path.getmtime(CACHE_FILE)
    if age < CACHE_TTL:
        with open(CACHE_FILE) as f:
            releases = json.load(f)

if releases is None:
    try:
        releases = fetch()
        os.makedirs(CACHE_DIR, exist_ok=True)
        with open(CACHE_FILE, "w") as f:
            json.dump(releases, f)
    except Exception as e:
        print(f"Warning: failed to fetch releases ({e}), trying stale cache", file=sys.stderr)
        if os.path.exists(CACHE_FILE):
            with open(CACHE_FILE) as f:
                releases = json.load(f)
        else:
            releases = []

os.makedirs("data", exist_ok=True)
with open(DATA_FILE, "w") as f:
    f.write("# Auto-generated by setup.sh\n")
    f.write("- name: Development\n  url: https://github.com/godopty/godopty\n")
    for rel in releases[:5]:
        tag = rel["tag_name"]
        url = rel["html_url"]
        f.write(f"- name: {tag}\n  url: {url}\n")
    f.write("- name: All releases \u2192\n  url: https://github.com/godopty/godopty/releases\n")

count = min(len(releases), 5)
print(f"Generated {DATA_FILE} with {count} releases")
PYEOF
