#!/usr/bin/env bash
set -euo pipefail
cd "$(dirname "$0")"

# Copy repo docs into assets/repo/ for Hugo resources.Get
mkdir -p assets/repo/crates/gpty-core
mkdir -p assets/repo/crates/gpty-ipc
mkdir -p assets/repo/crates/gpty-gdext
mkdir -p assets/repo/crates/gpty-cli
mkdir -p assets/repo/godot

cp ../README.md assets/repo/
cp ../CHANGELOG.md assets/repo/
cp ../ROADMAP.md assets/repo/
cp ../CONTRIBUTING.md assets/repo/
cp ../LICENSE assets/repo/
cp ../LICENSE-EXCEPTIONS.md assets/repo/
cp ../AGENTS.md assets/repo/
cp ../SECURITY.md assets/repo/
cp ../crates/gpty-core/README.md assets/repo/crates/gpty-core/
cp ../crates/gpty-ipc/README.md assets/repo/crates/gpty-ipc/
cp ../crates/gpty-gdext/README.md assets/repo/crates/gpty-gdext/
cp ../crates/gpty-cli/README.md assets/repo/crates/gpty-cli/
cp ../godot/README.md assets/repo/godot/

# ── Generate Versions dropdown from GitHub releases API ──────────────────
python3 << 'PYEOF'
import json, os, re, time, urllib.request, sys

CACHE_DIR = ".cache"
CACHE_FILE = os.path.join(CACHE_DIR, "releases.json")
DATA_FILE = "data/versions.yaml"
REPO = "godot-pty/gpty"
CACHE_TTL = 3600

def fetch():
    url = f"https://api.github.com/repos/{REPO}/releases?per_page=5"
    req = urllib.request.Request(url, headers={"User-Agent": "gpty-docs-setup"})
    with urllib.request.urlopen(req, timeout=10) as resp:
        return json.loads(resp.read())

def yaml_scalar(value):
    """A JSON string is also a valid YAML double-quoted scalar."""
    return json.dumps(str(value), ensure_ascii=False)

def safe_release(rel):
    """Validate remote release metadata before writing it into YAML.

    The API response is display data — but it is interpolated into the versions
    dropdown, so a compromised or malformed response could inject YAML entries
    (or a `javascript:` href) into the generated file. Keep only a conservative
    tag shape and a URL that points at this repository's release tags.
    """
    tag = str(rel.get("tag_name", ""))
    url = str(rel.get("html_url", ""))
    if not re.fullmatch(r"[A-Za-z0-9._+-]{1,64}", tag):
        return None
    if not re.fullmatch(rf"https://github\.com/{re.escape(REPO)}/releases/tag/[A-Za-z0-9._%+-]{{1,128}}", url):
        return None
    return tag, url

releases = None
if os.path.exists(CACHE_FILE):
    age = time.time() - os.path.getmtime(CACHE_FILE)
    if age < CACHE_TTL:
        with open(CACHE_FILE) as f:
            releases = json.load(f)

if releases is None:
    try:
        releases = fetch()
        os.makedirs(CACHE_DIR, exist_ok=True)
        with open(CACHE_FILE, "w") as f:
            json.dump(releases, f)
    except Exception as e:
        print(f"Warning: failed to fetch releases ({e}), trying stale cache", file=sys.stderr)
        if os.path.exists(CACHE_FILE):
            with open(CACHE_FILE) as f:
                releases = json.load(f)
        else:
            releases = []

os.makedirs("data", exist_ok=True)
emitted = 0
with open(DATA_FILE, "w") as f:
    f.write("# Auto-generated by setup.sh\n")
    f.write("- name: Development\n  url: https://github.com/godot-pty/gpty\n")
    for rel in releases[:5]:
        checked = safe_release(rel)
        if checked is None:
            print(f"Warning: skipped release metadata that failed validation: {rel!r}", file=sys.stderr)
            continue
        tag, url = checked
        f.write(f"- name: {yaml_scalar(tag)}\n  url: {yaml_scalar(url)}\n")
        emitted += 1
    f.write("- name: All releases \u2192\n  url: https://github.com/godot-pty/gpty/releases\n")

print(f"Generated {DATA_FILE} with {emitted} releases")
PYEOF
